### ISSUE TITLE
I believe I have reinstalled scipy, but I am still unable to open mglearn.  

### ISSUE THREAD

**Issue by jerrygraham** [amueller/mglearn#4]
I believe I have reinstalled scipy, but I am still unable to open mglearn.   This is what happens:

import scipy

import mglearn
Traceback (most recent call last):

  File "<ipython-input-8-e19748f92cd9>", line 1, in <module>
    import mglearn

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\__init__.py", line 1, in <module>
    from . import plots

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plots.py", line 14, in <module>
    from .plot_pca import plot_pca_illustration, plot_pca_whitening, plot_pca_faces

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plot_pca.py", line 1, in <module>
    from sklearn.decomposition import PCA

  File "C:\Users\User\Anaconda3\lib\site-packages\sklearn\decomposition\__init__.py", line 19, in <module>
    from .online_lda import LatentDirichletAllocation

  File "C:\Users\User\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py", line 22, in <module>
    from ..utils.fixes import logsumexp

ImportError: cannot import name 'logsumexp'

from scipy import ndimage

import mglearn
Traceback (most recent call last):

  File "<ipython-input-10-e19748f92cd9>", line 1, in <module>
    import mglearn

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\__init__.py", line 1, in <module>
    from . import plots

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plots.py", line 14, in <module>
    from .plot_pca import plot_pca_illustration, plot_pca_whitening, plot_pca_faces

  File "C:\Users\User\Anaconda3\lib\site-packages\mglearn\plot_pca.py", line 1, in <module>
    from sklearn.decomposition import PCA

  File "C:\Users\User\Anaconda3\lib\site-packages\sklearn\decomposition\__init__.py", line 19, in <module>
    from .online_lda import LatentDirichletAllocation

  File "C:\Users\User\Anaconda3\lib\site-packages\sklearn\decomposition\online_lda.py", line 22, in <module>
    from ..utils.fixes import logsumexp

ImportError: cannot import name 'logsumexp'

**Comment by amueller** [comment]
I think there is an issue with your scikit-learn installation. Can you try removing it, removing the folder ``C:\Users\User\Anaconda3\lib\site-packages\sklearn\`` and then installing it again with ``conda install scikit-learn``?

**Comment by amueller** [comment]
You might have updated the anaconda installation of scikit-learn with pip, which is not a good idea.

**Comment by jerrygraham** [comment]
Thank you.  I will try that.

On Thu, 26 Oct 2017 20:20:45 +0000 (UTC), Andreas Mueller wrote
> I think there is an issue with your scikit-learn installation. Can you try removing it, removing the folder C:\Users\User\Anaconda3\lib\site-packages\sklearn\ and then installing it again with conda install scikit-learn?
> 
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
>

Website: www.chess4.nyc

**Comment by amueller** [comment]
closing as no follow-up.
